### ISSUE TITLE
Migration of publish date and author data inconsistant

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-blog#279]
Improved migration in #277 still has some strange inconsistencies - logically the PublishDate and AuthorNames should be populated by the legacy BlogEntry Author and Date properties. 

After running the migration on some test data I have had some cases where this worked and then running the same migration ended up with empty AuthorName and a newly calculated PublishDate.

Will continue to look into this.

**Comment by camfindlay** [comment]
Further investigation, when running the task and logged in as an admin, the dates and authors migrate correctly.

**Comment by camfindlay** [comment]
@tractorcow any ideas on why the migration works correct when an admin is logged in but doesn't when running logged out but in dev mode? unsure what might be being triggered with the addition of admin permissions

**Comment by tractorcow** [comment]
I don't know =O

**Comment by camfindlay** [comment]
Could we mitigate this by enforcing an admin permission before the migration task can run?

**Comment by tractorcow** [comment]
We would have to find out why the admin permission is necessary. Do you have a sample DB I can run to replicate the issue locally?

**Comment by tractorcow** [comment]
This COULD have been fixed with https://github.com/silverstripe/silverstripe-blog/pull/287. Want to check?

**Comment by camfindlay** [comment]
Just run the migration and the author name and publish date when not logged in as admin still doesn't migrate.

**Comment by camfindlay** [comment]
Still an issue - tested against silverstripe.org codebase. I think we should enfore ADMIN permission in the migration task OR find the root of the issue.

**Comment by camfindlay** [comment]
I'm in the process of refactoring the migration from blog 1.0 to 2.0 pull request soon.

**Comment by camfindlay** [comment]
See #315

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
